FROM node:24-alpine AS base
WORKDIR /app

# --- Môi trường Development ---
FROM base AS development
COPY package*.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "dev"]

# --- Môi trường Build ---
FROM development AS builder
RUN npm run build

# --- Môi trường Production ---
FROM base AS production
COPY package*.json ./
# Chỉ cài các package cần cho production
RUN npm ci --only=production
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
# Copy file config nếu có (ví dụ next.config.js)
COPY --from=builder /app/next.config.mjs ./ 

EXPOSE 3000
CMD ["npm", "start"]