FROM node:24-alpine AS base
WORKDIR /app

# --- Môi trường Development ---
FROM base AS development
COPY package*.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "start:dev"]

# --- Môi trường Build ---
FROM development AS builder
RUN npm run build

# --- Môi trường Production ---
FROM base AS production
COPY package*.json ./
RUN npm ci --only=production
COPY --from=builder /app/dist ./dist

EXPOSE 4000
CMD ["npm", "run", "start:prod"]